export const categoryOptions: Array<{ label: string; value: string }> = [
  { label: 'Abwaermenutzung', value: 'abwaermenutzung' },
  { label: 'Algen', value: 'algen' },
  { label: 'Alltag', value: 'alltag' },
  { label: 'Arbeitsschutz', value: 'arbeitsschutz' },
  { label: 'Begruenung', value: 'begruenung' },
  { label: 'Beschichtung', value: 'beschichtung' },
  { label: 'Beschichtung/Farbe', value: 'beschichtung-farbe' },
  { label: 'Blue-Green Infrastructure', value: 'blue-green-infrastructure' },
  { label: 'Cool Pavement', value: 'cool-pavement' },
  { label: 'Dachbegruenung', value: 'dachbegruenung' },
  { label: 'Daemmung/Material', value: 'daemmung-material' },
  { label: 'Daten/Forecast', value: 'daten-forecast' },
  { label: 'Effizienz', value: 'effizienz' },
  { label: 'Energie', value: 'energie' },
  { label: 'Energieeffizienz', value: 'energieeffizienz' },
  { label: 'Entfeuchtung', value: 'entfeuchtung' },
  { label: 'Ernaehrung', value: 'ernaehrung' },
  { label: 'Fenster/Sonnenschutz', value: 'fenster-sonnenschutz' },
  { label: 'Fruehwarnung', value: 'fruehwarnung' },
  { label: 'Gebaeude', value: 'gebaeude' },
  { label: 'Gebaeude/Industrie', value: 'gebaeude-industrie' },
  { label: 'Gebaeude/Stadt', value: 'gebaeude-stadt' },
  { label: 'Gesundheit', value: 'gesundheit' },
  { label: 'Gruendach', value: 'gruendach' },
  { label: 'Gruene Fassade', value: 'gruene-fassade' },
  { label: 'Gruenwand', value: 'gruenwand' },
  { label: 'Haushalt', value: 'haushalt' },
  { label: 'Hitzeschutz', value: 'hitzeschutz' },
  { label: 'Hydration', value: 'hydration' },
  { label: 'Infrastruktur', value: 'infrastruktur' },
  { label: 'Innenraumklima', value: 'innenraumklima' },
  { label: 'Kaeltemittelarm', value: 'kaeltemittelarm' },
  { label: 'Kleidung/Textil', value: 'kleidung-textil' },
  { label: 'Klimatisierung', value: 'klimatisierung' },
  { label: 'Koerper', value: 'koerper' },
  { label: 'Komfort', value: 'komfort' },
  { label: 'Kommune', value: 'kommune' },
  { label: 'Kritische Infrastruktur', value: 'kritische-infrastruktur' },
  { label: 'Kuehlkleidung', value: 'kuehlkleidung' },
  { label: 'Kuehlung', value: 'kuehlung' },
  { label: 'Kuehlung ohne Strom', value: 'kuehlung-ohne-strom' },
  { label: 'Kuehlwesten/Module', value: 'kuehlwesten-module' },
  { label: 'Lueftung', value: 'lueftung' },
  { label: 'Luftqualitaet', value: 'luftqualitaet' },
  { label: 'Mikroklima', value: 'mikroklima' },
  { label: 'Monitoring', value: 'monitoring' },
  { label: 'Passive Kuehlung', value: 'passive-kuehlung' },
  { label: 'Person', value: 'person' },
  { label: 'Regenwasser', value: 'regenwasser' },
  { label: 'Resilienz', value: 'resilienz' },
  { label: 'Retrofit', value: 'retrofit' },
  { label: 'Risikogruppe', value: 'risikogruppe' },
  { label: 'Safety-Software', value: 'safety-software' },
  { label: 'Schlaf', value: 'schlaf' },
  { label: 'Smart-Glas/Beschichtung', value: 'smart-glas-beschichtung' },
  { label: 'Sofortmassnahme', value: 'sofortmassnahme' },
  { label: 'Solid-State', value: 'solid-state' },
  { label: 'Soziales', value: 'soziales' },
  { label: 'Sport/Arbeitsschutz', value: 'sport-arbeitsschutz' },
  { label: 'Stadt', value: 'stadt' },
  { label: 'Stadtplanung', value: 'stadtplanung' },
  { label: 'Technik', value: 'technik' },
  { label: 'Technik-light', value: 'technik-light' },
  { label: 'UV-Schutz', value: 'uv-schutz' },
  { label: 'Verdunstungskuehlung', value: 'verdunstungskuehlung' },
  { label: 'Verhalten', value: 'verhalten' },
  { label: 'Vorsorge', value: 'vorsorge' },
  { label: 'Waermepumpe/HVAC', value: 'waermepumpe-hvac' },
  { label: 'Wearable', value: 'wearable' },
  { label: 'Wellness', value: 'wellness' },
]
